### ISSUE TITLE
LocationManagerProxy?

### ISSUE THREAD

**Issue by jp1017** [amapapi/LocationService#3]
最新版删除了？

**Comment by jp1017** [comment]
最新版的都是LocationClient了，gogogogo

**Comment by amapapi** [comment]
最新版本定位SDK已经是以Service的方式提供定位能力，无需进行这层转换了，直接使用即可

**Comment by jp1017** [comment]
@amapapi 是这样的，我多个activity都要显示地图并定位，每个activity都要写service啊，有没有好的方法呢，或者地图直接设置经纬度，但是没找到这个方法呢，求破啊

**Comment by amapapi** [comment]
应该是需要这个方法吧？AMap.moveCamera(CameraUpdate update), CameraUpdateFactory有不同的方法来初始化一个CameraUpdate，在多个Activity都需要定位的情况下，考虑将定位模块封装下 以单例方式提供功能，后边我们会考虑提供开源的方式来处理这种场景

**Comment by jp1017** [comment]
好的，这个方法用过，原来还可以这样用，感谢。

PS：
去你们高德论坛，都不回复，还是这里靠谱些，哈哈
